DELETE FROM maps;
INSERT INTO maps (id, width, height, depth) VALUES (1, 5, 5, 1);
DELETE FROM tiles;
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 2, 0, 0, 1, 1, 1, 0, 0, 0, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 3, 0, 0, 1, 1, 1, 1, 0, 0, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 4, 0, 0, 1, 0, 0, 0, 0, 0, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 2, 1, 0, 1, 1, 0, 0, 0, 0, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 3, 1, 0, 1, 1, 0, 1, 0, 0, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 4, 1, 0, 1, 0, 0, 0, 0, 0, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 0, 2, 0, 1, 1, 0, 0, 0, 1, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 1, 2, 0, 1, 1, 0, 0, 0, 0, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 2, 2, 0, 1, 1, 0, 0, 0, 0, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 3, 2, 0, 1, 1, 0, 1, 0, 0, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 4, 2, 0, 1, 0, 0, 0, 0, 0, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 0, 3, 0, 1, 1, 0, 0, 1, 1, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 1, 3, 0, 1, 1, 0, 0, 1, 0, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 2, 3, 0, 1, 1, 0, 0, 1, 0, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 3, 3, 0, 1, 1, 0, 1, 1, 0, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 4, 3, 0, 1, 0, 0, 0, 0, 0, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 0, 4, 0, 1, 0, 0, 0, 0, 0, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 1, 4, 0, 1, 0, 0, 0, 0, 0, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 2, 4, 0, 1, 0, 0, 0, 0, 0, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 3, 4, 0, 1, 0, 0, 0, 0, 0, 1);
INSERT INTO tiles (map_id, room_id, object_id, x, y, z, underground, dug_out, wall_n, wall_e, wall_s, wall_w, floor) VALUES (1, -1, -1, 4, 4, 0, 1, 0, 0, 0, 0, 0, 1);
