DROP TABLE IF EXISTS races;
CREATE TABLE races (id INTEGER PRIMARY KEY, name TEXT NOT NULL, hold_behavior TEXT NOT NULL, move_behavior TEXT NOT NULL);
DROP TABLE IF EXISTS maps;
CREATE TABLE maps (id INTEGER PRIMARY KEY, width INTEGER NOT NULL, height INTEGER NOT NULL, depth INTEGER NOT NULL);